
export const learner = {
  name: "Arjun Mehta",
  level: 7,
  levelTitle: "Structured Trader",
  xp: 4280,
  xpToNextLevel: 5000,
  coins: 1240,
  streakDays: 12,
  membership: "premium", // "free" | "premium"
  todayMinutes: 42,
  certificates: 3,
  lessonsCompleted: 58,
  overallProgress: 64, // percentage across enrolled courses
  badges: [
    { id: "b1", label: "Pip Precision", icon: "target" },
    { id: "b2", label: "7-Day Streak", icon: "flame" },
    { id: "b3", label: "First Certificate", icon: "award" },
  ],
};

export const categories = [
  {
    id: "forex",
    name: "Forex Trading",
    tagline: "Majors, minors & exotics",
    courseCount: 14,
    icon: "candlestick",
    accent: "blue",
  },
  {
    id: "crypto",
    name: "Crypto Trading",
    tagline: "Spot, futures & on-chain flow",
    courseCount: 11,
    icon: "bitcoin",
    accent: "gold",
  },
  {
    id: "stocks",
    name: "Stock Market",
    tagline: "Equities & portfolio building",
    courseCount: 9,
    icon: "trending-up",
    accent: "green",
  },
  {
    id: "smc",
    name: "Smart Money Concept",
    tagline: "Liquidity & institutional flow",
    courseCount: 7,
    icon: "layers",
    accent: "blue",
  },
  {
    id: "ict",
    name: "ICT Concepts",
    tagline: "Order blocks & market structure",
    courseCount: 6,
    icon: "compass",
    accent: "gold",
  },
];

export const filterPills = [
  { id: "all", label: "All" },
  { id: "forex", label: "Forex" },
  { id: "crypto", label: "Crypto" },
  { id: "stocks", label: "Stock" },
  { id: "smc", label: "SMC" },
  { id: "ict", label: "ICT" },
  { id: "free", label: "Free" },
  { id: "premium", label: "Premium" },
  { id: "completed", label: "Completed" },
];

/**
 * Each course carries its own lesson list so the player can drive the
 * full watch -> quiz -> unlock-next flow from data alone.
 */
export const courses = [
  {
    id: "forex-beginner-masterclass",
    category: "forex",
    title: "Forex Beginner Masterclass",
    subtitle: "Everything you need to place your first structured trade",
    instructor: "Rohan Kapoor",
    instructorTitle: "Senior Forex Mentor, 9y prop desk experience",
    thumbnail: "candlestick-blue",
    level: "Beginner",
    duration: "6h 10m",
    lessonsCount: 15,
    students: 18420,
    rating: 4.9,
    ratingCount: 2310,
    language: "English",
    certificate: true,
    access: "premium",
    progress: 40,
    description:
      "A ground-up walkthrough of the forex market — pairs, sessions, spreads, leverage and margin — built for traders who want the mechanics right before risking capital.",
    lessons: [
      {
        id: "l1",
        title: "Introduction to Forex Market",
        estimatedMinutes: 18,
        objective:
          "Understand what forex is, how currency pairs quote, and the mechanics behind every order you'll place.",
        requiredKnowledge: "None — this is your starting point.",
        difficulty: "Beginner",
        learningOutcomes: [
          "Define the forex market and its daily turnover",
          "Read a currency pair quote correctly",
          "Explain bid/ask and where spread comes from",
        ],
        importantConcepts: [
          "What is Forex",
          "Currency Pair",
          "Bid / Ask",
          "Spread",
          "Pip",
          "Lot Size",
          "Leverage",
          "Margin",
          "Trading Sessions",
        ],
        riskWarning:
          "Forex trading involves significant risk of loss and is not suitable for all investors. Leverage can amplify both gains and losses.",
        videoProvider: "youtube",
        videoId: "GPfzQKq3Q4w",
        chapters: [
          { time: "0:00", label: "Welcome & course map" },
          { time: "3:20", label: "What moves currency prices" },
          { time: "8:45", label: "Reading a quote: EUR/USD" },
          { time: "13:10", label: "Pips, lots & leverage" },
        ],
        transcriptExcerpt:
          "We open by framing the forex market as the largest, most liquid market in the world, then walk through exactly how a EUR/USD quote is built from bid to ask before introducing pip value and lot sizing with on-screen examples.",
        resources: [
          { label: "Session Overlap Cheat Sheet", type: "pdf" },
          { label: "Pip Value Calculator", type: "xlsx" },
        ],
        quiz: {
          passingScore: 80,
          questions: [
            {
              id: "q1",
              question: "What is a Pip?",
              options: [
                "A trade order",
                "The smallest price movement a pair can make",
                "A broker fee",
                "A lot size",
              ],
              correctIndex: 1,
            },
            {
              id: "q2",
              question: "What is Spread?",
              options: [
                "Difference between Bid and Ask",
                "Leverage ratio",
                "Broker commission",
                "Account risk",
              ],
              correctIndex: 0,
            },
            {
              id: "q3",
              question: "Which trading session has the highest liquidity?",
              options: ["Sydney", "Tokyo", "London", "Weekend"],
              correctIndex: 2,
            },
          ],
        },
      },
      {
        id: "l2",
        title: "Market Structure",
        estimatedMinutes: 22,
        objective:
          "Learn how leverage and margin actually work together, and how professional traders size a position before entry.",
        requiredKnowledge: "Lesson 1 — Introduction to Forex Market",
        difficulty: "Beginner",
        learningOutcomes: [
          "Calculate required margin for a position",
          "Explain how leverage changes exposure, not just profit",
          "Identify swing highs/lows that define structure",
        ],
        importantConcepts: [
          "Leverage",
          "Margin",
          "Market Structure",
          "Swing Highs & Lows",
          "Trend vs Range",
        ],
        riskWarning:
          "Higher leverage increases the speed at which losses can reach your account, not only your gains.",
        videoProvider: "youtube",
        videoId: "GPfzQKq3Q4w",
        chapters: [
          { time: "0:00", label: "Recap: pips & lots" },
          { time: "4:00", label: "Leverage vs margin" },
          { time: "10:30", label: "Spotting market structure" },
        ],
        transcriptExcerpt:
          "This lesson separates two commonly confused terms — leverage and margin — using a funded example account, then shifts into identifying structure on a live EUR/USD chart.",
        resources: [{ label: "Margin Calculator Template", type: "xlsx" }],
        quiz: {
          passingScore: 80,
          questions: [
            {
              id: "q4",
              question: "Leverage means...",
              options: [
                "Borrowed capital that increases market exposure",
                "A trading indicator",
                "A broker fee",
                "A type of currency pair",
              ],
              correctIndex: 0,
            },
            {
              id: "q5",
              question: "Margin means...",
              options: [
                "Required deposit to open a leveraged position",
                "Guaranteed profit",
                "A trading loss",
                "Broker commission",
              ],
              correctIndex: 0,
            },
          ],
        },
      },
      {
        id: "l3",
        title: "Risk Management",
        estimatedMinutes: 20,
        objective: "Build a risk framework you can repeat on every trade.",
        requiredKnowledge: "Lessons 1–2",
        difficulty: "Beginner",
        learningOutcomes: [
          "Set stop-loss and take-profit with a fixed R multiple",
          "Cap risk per trade to a percentage of account equity",
        ],
        importantConcepts: ["Stop Loss", "Take Profit", "Risk per Trade", "R Multiple"],
        riskWarning: "No risk framework eliminates the possibility of loss.",
        videoProvider: "youtube",
        videoId: "GPfzQKq3Q4w",
        chapters: [{ time: "0:00", label: "Position sizing basics" }],
        transcriptExcerpt: "",
        resources: [{ label: "Risk Calculator", type: "pdf" }],
        locked: true,
        quiz: { passingScore: 80, questions: [] },
      },
      {
        id: "l4",
        title: "Trading Psychology",
        estimatedMinutes: 16,
        objective: "Recognize the emotional patterns that break good strategies.",
        requiredKnowledge: "Lessons 1–3",
        difficulty: "Beginner",
        importantConcepts: ["Discipline", "FOMO", "Revenge Trading"],
        riskWarning: "",
        videoProvider: "youtube",
        videoId: "GPfzQKq3Q4w",
        chapters: [],
        transcriptExcerpt: "",
        resources: [],
        locked: true,
        quiz: { passingScore: 80, questions: [] },
      },
      {
        id: "l5",
        title: "Building Your Trading Plan",
        estimatedMinutes: 19,
        objective: "Assemble everything into one written, repeatable plan.",
        requiredKnowledge: "Lessons 1–4",
        difficulty: "Beginner",
        importantConcepts: ["Trading Plan", "Journaling", "Review Cycle"],
        riskWarning: "",
        videoProvider: "youtube",
        videoId: "GPfzQKq3Q4w",
        chapters: [],
        transcriptExcerpt: "",
        resources: [],
        locked: true,
        quiz: { passingScore: 80, questions: [] },
      },
    ],
  },
  {
    id: "crypto-price-action-mastery",
    category: "crypto",
    title: "Crypto Price Action Mastery",
    subtitle: "Reading BTC & ETH charts without indicator clutter",
    instructor: "Simran Kaur",
    instructorTitle: "Crypto Derivatives Analyst",
    thumbnail: "candlestick-gold",
    level: "Intermediate",
    duration: "8h 40m",
    lessonsCount: 22,
    students: 12980,
    rating: 4.8,
    ratingCount: 1540,
    language: "English",
    certificate: true,
    access: "premium",
    progress: 0,
    description:
      "Pure price-action reading for crypto majors — structure, liquidity sweeps and volatility regimes, taught on live BTC/ETH charts.",
    lessons: [
      {
        id: "l1",
        title: "Introduction to Price Action Trading",
        estimatedMinutes: 20,
        objective: "Understand why price action leads every indicator.",
        requiredKnowledge: "Basic candlestick reading",
        difficulty: "Intermediate",
        learningOutcomes: ["Identify impulse vs corrective moves", "Mark higher-timeframe bias"],
        importantConcepts: ["Impulse Move", "Correction", "Higher Timeframe Bias"],
        riskWarning: "Crypto assets are highly volatile and can move sharply against open positions.",
        videoProvider: "youtube",
        videoId: "SSo_EIwHSd4",
        chapters: [{ time: "0:00", label: "Why price action first" }],
        transcriptExcerpt:
          "We start on the BTC/USDT weekly chart to show how every indicator lags the raw candle data it's built from.",
        resources: [{ label: "BTC Liquidity Map Template", type: "pdf" }],
        quiz: {
          passingScore: 80,
          questions: [
            {
              id: "q1",
              question: "An impulse move is best described as...",
              options: [
                "A slow, corrective pullback",
                "A strong directional move with the trend",
                "A sideways consolidation",
                "A broker-side execution delay",
              ],
              correctIndex: 1,
            },
          ],
        },
      },
    ],
  },
  {
    id: "stock-market-investing",
    category: "stocks",
    title: "Stock Market Investing",
    subtitle: "From opening an account to reading a balance sheet",
    instructor: "Devika Rao",
    instructorTitle: "Equity Research Associate",
    thumbnail: "candlestick-green",
    level: "Beginner",
    duration: "7h 05m",
    lessonsCount: 18,
    students: 9410,
    rating: 4.7,
    ratingCount: 980,
    language: "English",
    certificate: true,
    access: "premium",
    progress: 0,
    description:
      "A practical on-ramp to equity investing — account setup, order types, and the fundamentals that separate a company from a ticker.",
    lessons: [
      {
        id: "l1",
        title: "How the Stock Market Actually Works",
        estimatedMinutes: 17,
        objective: "Understand exchanges, order books and settlement.",
        requiredKnowledge: "None",
        difficulty: "Beginner",
        learningOutcomes: ["Explain how a buy order matches a sell order"],
        importantConcepts: ["Exchange", "Order Book", "Settlement"],
        riskWarning: "Equity values can fall as well as rise; past performance is not indicative of future results.",
        videoProvider: "youtube",
        videoId: "p7HKvqRI_Bo",
        chapters: [{ time: "0:00", label: "Exchanges & order books" }],
        transcriptExcerpt: "We trace an order from your broker app to the exchange order book and back.",
        resources: [{ label: "Order Types Reference", type: "pdf" }],
        quiz: {
          passingScore: 80,
          questions: [
            {
              id: "q1",
              question: "A limit order will only execute...",
              options: [
                "At the market price immediately",
                "At your specified price or better",
                "After the exchange closes",
                "Only for options",
              ],
              correctIndex: 1,
            },
          ],
        },
      },
    ],
  },
  {
    id: "ict-concepts",
    category: "ict",
    title: "ICT Concepts",
    subtitle: "Order blocks, FVGs and market maker models",
    instructor: "Rohan Kapoor",
    instructorTitle: "Senior Forex Mentor",
    thumbnail: "candlestick-blue",
    level: "Advanced",
    duration: "5h 30m",
    lessonsCount: 12,
    students: 7620,
    rating: 4.9,
    ratingCount: 860,
    language: "English",
    certificate: true,
    access: "premium",
    progress: 0,
    description:
      "A focused breakdown of ICT's core toolkit — order blocks, fair value gaps and liquidity draws — applied to live forex structure.",
    lessons: [
      {
        id: "l1",
        title: "Order Blocks & Fair Value Gaps",
        estimatedMinutes: 24,
        objective: "Identify institutional footprints on a raw chart.",
        requiredKnowledge: "Market structure basics",
        difficulty: "Advanced",
        learningOutcomes: ["Mark a bullish and bearish order block", "Spot a fair value gap"],
        importantConcepts: ["Order Block", "Fair Value Gap", "Liquidity Draw"],
        riskWarning: "Advanced concepts still carry full market risk — position size accordingly.",
        videoProvider: "youtube",
        videoId: "GPfzQKq3Q4w",
        chapters: [{ time: "0:00", label: "Marking order blocks live" }],
        transcriptExcerpt: "",
        resources: [],
        quiz: {
          passingScore: 80,
          questions: [
            {
              id: "q1",
              question: "A Fair Value Gap typically forms from...",
              options: [
                "Three consecutive candles with an imbalance between wicks",
                "A broker's spread widening",
                "A change in account leverage",
                "A missed economic news release",
              ],
              correctIndex: 0,
            },
          ],
        },
      },
    ],
  },
  {
    id: "smc-bootcamp",
    category: "smc",
    title: "SMC Bootcamp",
    subtitle: "Trading with, not against, institutional liquidity",
    instructor: "Simran Kaur",
    instructorTitle: "Crypto Derivatives Analyst",
    thumbnail: "candlestick-gold",
    level: "Intermediate",
    duration: "6h 50m",
    lessonsCount: 20,
    students: 8340,
    rating: 4.8,
    ratingCount: 1120,
    language: "English",
    certificate: true,
    access: "premium",
    progress: 0,
    description:
      "Smart Money Concept from the ground up — liquidity pools, breaks of structure, and how to build entries around them.",
    lessons: [
      {
        id: "l1",
        title: "Liquidity Pools & Breaks of Structure",
        estimatedMinutes: 21,
        objective: "Map liquidity before you plan an entry.",
        requiredKnowledge: "Market structure basics",
        difficulty: "Intermediate",
        learningOutcomes: ["Mark buy-side and sell-side liquidity", "Define a break of structure"],
        importantConcepts: ["Liquidity Pool", "Break of Structure", "Change of Character"],
        riskWarning: "",
        videoProvider: "youtube",
        videoId: "SSo_EIwHSd4",
        chapters: [{ time: "0:00", label: "Mapping liquidity pools" }],
        transcriptExcerpt: "",
        resources: [],
        quiz: {
          passingScore: 80,
          questions: [
            {
              id: "q1",
              question: "A Break of Structure (BOS) confirms...",
              options: [
                "A continuation of the current trend",
                "A broker execution error",
                "A margin call",
                "A change in trading session",
              ],
              correctIndex: 0,
            },
          ],
        },
      },
    ],
  },
  {
    id: "forex-free-intro",
    category: "forex",
    title: "Forex Trading — Free Starter",
    subtitle: "A no-cost taste of the full Masterclass",
    instructor: "Rohan Kapoor",
    instructorTitle: "Senior Forex Mentor",
    thumbnail: "candlestick-blue",
    level: "Beginner",
    duration: "45m",
    lessonsCount: 3,
    students: 41200,
    rating: 4.6,
    ratingCount: 5200,
    language: "English",
    certificate: false,
    access: "free",
    progress: 0,
    description: "Three free lessons covering the absolute basics before you commit to the full path.",
    lessons: [
      {
        id: "l1",
        title: "What Is Forex, Really?",
        estimatedMinutes: 12,
        objective: "Get oriented before anything else.",
        requiredKnowledge: "None",
        difficulty: "Beginner",
        learningOutcomes: ["Explain forex in one sentence to a friend"],
        importantConcepts: ["Currency Pair", "Base & Quote"],
        riskWarning: "",
        videoProvider: "youtube",
        videoId: "GPfzQKq3Q4w",
        chapters: [],
        transcriptExcerpt: "",
        resources: [],
        quiz: {
          passingScore: 80,
          questions: [
            {
              id: "q1",
              question: "In EUR/USD, EUR is the...",
              options: ["Quote currency", "Base currency", "Broker fee", "Lot size"],
              correctIndex: 1,
            },
          ],
        },
      },
    ],
  },
];

export const membershipBenefits = [
  { label: "Unlimited Courses", icon: "infinity" },
  { label: "Verified Certificates", icon: "award" },
  { label: "Community Access", icon: "users" },
  { label: "1:1 Mentor Support", icon: "message-circle" },
  { label: "Trading Journal", icon: "book-open" },
  { label: "Live Signals", icon: "radio" },
  { label: "Downloadable Resources", icon: "download" },
];

export const communityThreads = [
  {
    id: "c1",
    user: "Priya S.",
    question: "How tight should my stop be on a London-session EUR/USD entry?",
    replies: 14,
    mentorAnswered: true,
  },
  {
    id: "c2",
    user: "Karan V.",
    question: "Is a fair value gap still valid after price returns to it twice?",
    replies: 9,
    mentorAnswered: true,
  },
  {
    id: "c3",
    user: "Neha T.",
    question: "Best way to journal losing trades without it becoming discouraging?",
    replies: 21,
    mentorAnswered: false,
  },
];

export const downloadableResources = [
  { label: "Trading Checklist", type: "pdf", size: "220 KB" },
  { label: "Trading Journal Template", type: "xlsx", size: "480 KB" },
  { label: "Risk Calculator", type: "xlsx", size: "160 KB" },
  { label: "Session Overlap Indicators", type: "zip", size: "1.2 MB" },
  { label: "Chart Marking Templates", type: "zip", size: "3.4 MB" },
];

export const leaderboard = [
  { rank: 1, name: "Yash P.", xp: 18420 },
  { rank: 2, name: "Meera D.", xp: 17110 },
  { rank: 3, name: "Arjun Mehta", xp: 4280, isYou: true },
  { rank: 4, name: "Sana K.", xp: 15990 },
];
